/**
 * Write a JavaScript program to create an object with the same keys as the provided object. 
 * It will also generate values generated by running the provided function for each value.
 */

// my sol
function mapValues(obj, fn) {

    return Object.keys(obj)
    .reduce((acc, cur) => {
        acc[cur] = fn(obj[cur], cur, obj);
        return acc;
    }, {});
}

const users = {
  fred: { user: 'fred', age: 40 },
  pebbles: { user: 'pebbles', age: 1 }
};
console.log(mapValues(users, u => u.age)); // Outputs: { fred: 40, pebbles: 1 }